import { useAtom } from "jotai"
import { ChevronRight, Plus } from "lucide-react"

import { useState } from "react"
import { Link, useParams } from "react-router"

import RestaurantMenuPageSkeleton from "@/components/ui/Feedback/restaurant-menu-skeleton"
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel"
import CartModule from "@/components/ui/cart/cart-module"
import HeroCard from "@/components/ui/restaurant/hero-card"

import hero from "@/assets/images/burger-imge.webp"
import { addToCartAtom } from "@/atoms"
import { useRestaurant } from "@/hooks/use-restaurants"
import type { CartItem } from "@/types/cart"
import type { MenuItem } from "@/types/restaurants"

const categories = [
    { id: 1, name: "الكل" },
    { id: 2, name: "طعام" },
    { id: 3, name: "مشروبات" },
    { id: 4, name: "سلطات" },
    { id: 5, name: "فتات" },
]

export default function Menu() {
    const { id } = useParams()
    const [hoveredItem, setHoveredItem] = useState<number | null>(null)
    const { value: rest, loading } = useRestaurant(id ?? "")
    const [, addToCart] = useAtom(addToCartAtom)

    const handleAddToCart = (e: React.MouseEvent, item: MenuItem) => {
        e.preventDefault()
        e.stopPropagation()

        // Get first variation as default, or use base price
        const defaultVariation = item.differents?.[0]

        // Create cart item with default values
        const cartItem: CartItem = {
            id: "", // Will be generated by addToCartAtom
            productId: item.id,
            name: item.name,
            description: item.description,
            price: item.price,
            quantity: 1,
            image: item.image,
            variation: defaultVariation
                ? {
                      id: defaultVariation.id,
                      name: defaultVariation.name,
                      price: defaultVariation.price || 0,
                  }
                : undefined,
            addons: [],
            restaurantId: id,
        }

        addToCart(cartItem)
    }

    if (loading) return <RestaurantMenuPageSkeleton />

    return (
        <div className="min-h-screen ">
            <div className="relative w-full shrink-0">
                <Link
                    to={`/restaurant/${id}/product_details/${rest?.id}`}
                    className="absolute top-4 right-4 md:top-6 md:right-6 z-10 rounded-lg py-2.5 px-3 bg-white/90 backdrop-blur-sm shadow-lg hover:bg-white transition-all duration-200"
                    aria-label="Back to menu"
                >
                    <ChevronRight className="w-5 h-5 md:w-6 md:h-6 text-gray-700" />
                </Link>

                <div className="w-full overflow-hidden h-[161px] sm:h-64 md:h-96 lg:h-[500px]">
                    <img src={hero} alt="Restaurant Hero" className="w-full h-full object-cover" />
                </div>

                <HeroCard title={rest?.name || ""} description={rest?.description || ""} image={rest?.image || ""} />
            </div>

            <div className="container relative mx-auto px-4">
                <Carousel
                    opts={{
                        align: "start",
                        dragFree: true,
                        containScroll: "trimSnaps",
                    }}
                    className="mb-[24px] md:mt-[100px] mt-[72px]"
                >
                    <CarouselContent className="gap-x-2">
                        {categories.map((category) => (
                            <CarouselItem key={category.id} className="basis-auto pl-2 md:pl-4">
                                <button
                                    className={`rounded-[12px] px-6 py-3 text-sm font-medium transition-all duration-200 whitespace-nowrap
                                        ${
                                            category.name === "الكل"
                                                ? "bg-primary text-white   "
                                                : "bg-white text-gray-700  border-1  border-gray-200 "
                                        }
                                    `}
                                >
                                    {category.name}
                                </button>
                            </CarouselItem>
                        ))}
                    </CarouselContent>
                </Carousel>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pb-8">
                    {rest &&
                        rest?.menu?.map((item: MenuItem) => (
                            <Link
                                key={item.id}
                                to={`/restaurant/${id}/product_details/${item?.id}`}
                                className="group cursor-pointer overflow-hidden border-b border-gray-600 block"
                            >
                                <div className="flex p-4">
                                    <div className="flex-shrink-0">
                                        <div className="relative">
                                            <img
                                                src={item.image}
                                                alt={item.name}
                                                className="size-[70px] md:w-24 md:h-24 rounded-2xl object-cover shadow-sm group-hover:shadow-md transition-shadow duration-300"
                                            />
                                            <div className="absolute inset-0 rounded-2xl bg-primary/5 group-hover:bg-primary/10 transition-colors duration-300" />
                                        </div>
                                    </div>

                                    <div className="flex-1 pr-4 flex flex-col justify-between">
                                        <div>
                                            <div className="flex items-start justify-between">
                                                <h3 className="text-lg font-bold text-gray-900 line-clamp-1">
                                                    {item?.name}
                                                </h3>
                                                <p className="text-lg font-bold text-secondary whitespace-nowrap mr-2">
                                                    {item.price} ر.س
                                                </p>
                                            </div>
                                        </div>

                                        <div className="flex items-center justify-between mt-3">
                                            <p className="text-sm text-gray-600 line-clamp-2 leading-relaxed">
                                                {item.description}
                                            </p>

                                            <button
                                                onClick={(e) => handleAddToCart(e, item)}
                                                onMouseEnter={() => setHoveredItem(item?.id)}
                                                onMouseLeave={() => setHoveredItem(null)}
                                                className="p-2 rounded-xl border border-primary text-primary transition-all duration-200 flex items-center justify-center hover:bg-primary hover:text-white"
                                                aria-label="Add to cart"
                                            >
                                                {hoveredItem === item?.id ? (
                                                    <Plus className="w-4 h-4" />
                                                ) : (
                                                    <ChevronRight className="w-4 h-4 rotate-180" />
                                                )}
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </Link>
                        ))}
                </div>
                <CartModule />
            </div>
        </div>
    )
}
