import { useAtom } from "jotai"

import { useState } from "react"

import { addToCartAtom } from "@/atoms"
import type { CartItem } from "@/types/cart"
import type { MenuItem, Restaurant } from "@/types/restaurants"

import { useRestaurant } from "./use-restaurants"

interface UseMenu {
    hoveredItem: number | null
    setHoveredItem: (itemId: number | null) => void
    rest: Restaurant | undefined
    loading: boolean
    handleAddToCart: (e: React.MouseEvent, item: MenuItem) => void
    id: string
}
export const useMenu = (id: string): UseMenu => {
    const [hoveredItem, setHoveredItem] = useState<number | null>(null)
    const { value: rest, loading } = useRestaurant(id ?? "")
    const [, addToCart] = useAtom(addToCartAtom)

    const handleAddToCart = (e: React.MouseEvent, item: MenuItem) => {
        e.preventDefault()
        e.stopPropagation()

        // Get first variation as default, or use base price
        const defaultVariation = item.differents?.[0]

        // Create cart item with default values
        const cartItem: CartItem = {
            id: "", // Will be generated by addToCartAtom
            productId: item.id,
            name: item.name,
            description: item.description,
            price: item.price,
            quantity: 1,
            image: item.image,
            variation: defaultVariation
                ? {
                      id: defaultVariation.id,
                      name: defaultVariation.name,
                      price: defaultVariation.price || 0,
                  }
                : undefined,
            addons: [],
            restaurantId: id,
        }

        addToCart(cartItem)
    }

    return {
        hoveredItem,
        setHoveredItem,
        rest,
        loading,
        handleAddToCart,
        id,
    }
}
